// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRsm7AJBpiFvkzkTOBrBeGfzqYy8bC1mM',
    appId: '1:355921287545:web:f0f74d33256f6122a937a8',
    messagingSenderId: '355921287545',
    projectId: 'driving-test-41015',
    authDomain: 'driving-test-41015.firebaseapp.com',
    databaseURL: 'https://driving-test-41015-default-rtdb.firebaseio.com',
    storageBucket: 'driving-test-41015.firebasestorage.app',
    measurementId: 'G-EP2PG1XRYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfVq3RbPiTyDEz_3lJ_fqOk5ZmV0GX7t8',
    appId: '1:355921287545:android:b35ddb7f82677b89a937a8',
    messagingSenderId: '355921287545',
    projectId: 'driving-test-41015',
    databaseURL: 'https://driving-test-41015-default-rtdb.firebaseio.com',
    storageBucket: 'driving-test-41015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBk7KWQe7AKlSjg88AsGQYU2uGw2oYe8c',
    appId: '1:752265630130:ios:06ba4713ecc5a58c57d4ab',
    messagingSenderId: '752265630130',
    projectId: 'driving-license-manager',
    storageBucket: 'driving-license-manager.firebasestorage.app',
    iosBundleId: 'com.example.mob4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBk7KWQe7AKlSjg88AsGQYU2uGw2oYe8c',
    appId: '1:752265630130:ios:06ba4713ecc5a58c57d4ab',
    messagingSenderId: '752265630130',
    projectId: 'driving-license-manager',
    storageBucket: 'driving-license-manager.firebasestorage.app',
    iosBundleId: 'com.example.mob4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRsm7AJBpiFvkzkTOBrBeGfzqYy8bC1mM',
    appId: '1:355921287545:web:1524727a94cd282aa937a8',
    messagingSenderId: '355921287545',
    projectId: 'driving-test-41015',
    authDomain: 'driving-test-41015.firebaseapp.com',
    databaseURL: 'https://driving-test-41015-default-rtdb.firebaseio.com',
    storageBucket: 'driving-test-41015.firebasestorage.app',
    measurementId: 'G-K1FNFM6KF6',
  );

}