import '../models/test_models.dart';

class AppData {
  static List<Remark> remarks = [
    Remark(remarkId: 1,
        text: 'Not operating handbrake sufficiently - rolling back towards traffic',
        testId: '1'),
    Remark(
        remarkId: 2, text: 'Depressing clutch whilst cornering', testId: '2'),
    Remark(remarkId: 3, text: 'Holding the inside of the wheel', testId: ''),
    Remark(remarkId: 4, text: 'Steering too late', testId: ''),
    Remark(remarkId: 5, text: 'Allowing the wheel to self-center', testId: ''),
    Remark(
        remarkId: 6, text: 'Not allowing for any other road users', testId: ''),
    Remark(
        remarkId: 7, text: 'Becoming dangerously close to others', testId: ''),
    Remark(remarkId: 8, text: 'Wrong controls used', testId: ''),
    Remark(remarkId: 9, text: 'Late reaction', testId: ''),
    Remark(remarkId: 10,
        text: 'Confused other road users by an unnecessary signal',
        testId: ''),
    Remark(remarkId: 11, text: 'Not stopping at a stop line', testId: ''),
    Remark(remarkId: 12, text: 'Stopping on a pedestrian crossing', testId: ''),
    Remark(remarkId: 13, text: 'Crossing a continuous white line', testId: ''),
    Remark(remarkId: 14, text: 'Not stopping at a red light', testId: ''),
    Remark(remarkId: 15, text: 'Not stopping at an amber light', testId: ''),
    Remark(remarkId: 16,
        text: 'Not stopping when directed by a police officer regulating traffic',
        testId: ''),
    Remark(
        remarkId: 17, text: 'Not giving way if all lights are off', testId: ''),
    Remark(remarkId: 18,
        text: 'Not keeping a safe distance when queueing behind traffic',
        testId: ''),
    Remark(remarkId: 19,
        text: 'Failure to drive when the road is clear at a junction',
        testId: ''),
    Remark(remarkId: 20, text: 'Late braking', testId: ''),
    Remark(remarkId: 21,
        text: 'Bad position, unnecessarily blocking other traffic before turning',
        testId: ''),
    Remark(
        remarkId: 22, text: 'Rushing when there is little space', testId: ''),
    Remark(remarkId: 23,
        text: 'Not recognizing the speed of approaching traffic',
        testId: ''),
    Remark(remarkId: 24, text: 'Significant zigzag', testId: ''),
    Remark(remarkId: 25, text: 'Changing lanes suddenly', testId: ''),
    Remark(remarkId: 26,
        text: 'Demanding priority when it is not yours',
        testId: ''),
    Remark(remarkId: 27,
        text: 'Moving on when waved by other drivers when it is not safe',
        testId: ''),
    Remark(remarkId: 28, text: 'Not giving way to larger vehicles', testId: ''),
    Remark(remarkId: 29,
        text: 'Engaging two lanes while turning right or left - swan neck steering',
        testId: ''),
    Remark(remarkId: 30, text: 'Gear change too late', testId: ''),
    Remark(remarkId: 31,
        text: 'Starting the engine in gear causing the vehicle to move forward',
        testId: ''),
    Remark(remarkId: 32,
        text: 'Severe jerky or sudden use of the accelerator',
        testId: ''),
    Remark(remarkId: 33,
        text: 'Clutch biting too much - excessive acceleration',
        testId: ''),
    Remark(remarkId: 34,
        text: 'Jerky or sudden release of the clutch',
        testId: ''),
    Remark(remarkId: 35, text: 'Stalling', testId: ''),
    Remark(remarkId: 36, text: 'Unable to follow a straight line', testId: ''),
    Remark(remarkId: 37, text: 'Large overcorrection of the wheel', testId: ''),
    Remark(remarkId: 38, text: 'Steering too late', testId: ''),
    Remark(remarkId: 39,
        text: 'Not steering sufficiently at the correct time',
        testId: ''),
    Remark(remarkId: 40, text: 'No checking in mirrors', testId: ''),
    Remark(remarkId: 41, text: 'No checking in blind spot', testId: ''),
    Remark(remarkId: 42,
        text: 'Depressing the clutch too early before stopping',
        testId: ''),
    Remark(remarkId: 43,
        text: 'Failure to recognize road surfaces which demand careful braking',
        testId: ''),
    Remark(remarkId: 44,
        text: 'Not re-signaling if it self-cancels early',
        testId: ''),
    Remark(remarkId: 45,
        text: 'Not signaling before turning right or left',
        testId: ''),
    Remark(remarkId: 46,
        text: 'Not responding correctly to a hazard sign',
        testId: ''),
    Remark(remarkId: 47, text: 'Stopping on a yellow box', testId: ''),
    Remark(remarkId: 48,
        text: 'Not recognizing a phase change in traffic light',
        testId: ''),
    Remark(remarkId: 49,
        text: 'Not responding correctly to a police officer regulating traffic',
        testId: ''),
    Remark(remarkId: 50, text: 'Not looking well ahead', testId: ''),
    Remark(remarkId: 51,
        text: 'Not recognizing which driver has priority',
        testId: ''),
    Remark(remarkId: 52,
        text: 'Driving unnecessarily close to the road edge',
        testId: ''),
    Remark(remarkId: 53, text: 'Minor zigzag', testId: ''),
    Remark(remarkId: 54,
        text: 'Wheels not straight as the car becomes straight',
        testId: ''),
    Remark(remarkId: 55,
        text: 'Not using the gear to match speed and conditions',
        testId: ''),
  ];
  static List<Vehicle> vehicles = [
  {'vehicle_id': 1, 'description': 'Car'},
  {'vehicle_id': 2, 'description': 'Motorbike'},
  ].map((vehicle) => Vehicle.fromMap(vehicle)).toList();
  static int maxNumberOfRemarksForLoosing = 3;
}
